services:
  web:
    build: .
    command: [python, manage.py, runserver, "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  db:
    image: postgres:18-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis_data:/data
    env_file: .env
    command: redis-server --appendonly yes  --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep -q PONG" ]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: always
    env_file: .env
    hostname: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/10-deprecated.conf:ro
    ports:
      - 127.0.0.1:15672:15672
    expose:
      - 5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    build: .
    command: [ celery, --app=F1_backend, worker, --loglevel=INFO ]
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      rabbitmq: { condition: service_healthy }
      db: { condition: service_healthy }
      migrate:
        condition: service_completed_successfully

  beat:
    build: .
    command: [ celery, --app=F1_backend, beat, --loglevel=INFO]
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "python manage.py migrate --noinput && python manage.py collectstatic --noinput"]

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
